# Generated by Django 6.0 on 2025-12-24 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
