# Generated by Django 6.0 on 2025-12-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
